/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AbsoulutelycaptivatingRouteImport } from './routes/absoulutelycaptivating'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AbsoulutelycaptivatingRoute = AbsoulutelycaptivatingRouteImport.update({
  id: '/absoulutelycaptivating',
  path: '/absoulutelycaptivating',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/absoulutelycaptivating': typeof AbsoulutelycaptivatingRoute
  '/analytics': typeof AnalyticsRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/absoulutelycaptivating': typeof AbsoulutelycaptivatingRoute
  '/analytics': typeof AnalyticsRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/absoulutelycaptivating': typeof AbsoulutelycaptivatingRoute
  '/analytics': typeof AnalyticsRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/absoulutelycaptivating' | '/analytics' | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/absoulutelycaptivating' | '/analytics' | '/api/chat'
  id: '__root__' | '/' | '/absoulutelycaptivating' | '/analytics' | '/api/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbsoulutelycaptivatingRoute: typeof AbsoulutelycaptivatingRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/absoulutelycaptivating': {
      id: '/absoulutelycaptivating'
      path: '/absoulutelycaptivating'
      fullPath: '/absoulutelycaptivating'
      preLoaderRoute: typeof AbsoulutelycaptivatingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbsoulutelycaptivatingRoute: AbsoulutelycaptivatingRoute,
  AnalyticsRoute: AnalyticsRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
